name: CI Test

on:
  push:
    branches: [ main, DEV_Code ]
  pull_request:
    branches: [ main, DEV_Code ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/arm64 -t basketball-analysis --load .

    - name: Run Docker container
      run: |
        docker run -d --name basketball-container \
          -e ASSETS_DIR=/app/assets \
          -e OUTPUT_DIR=/app/output \
          -e LOG_DIR=/app/output/logs \
          -e VIDEO_DIR=/app/output/simulations \
          -e TRACKING_DIR=/app/output/tracking_data \
          basketball-analysis
        docker ps

    - name: Wait for scripts to complete
      run: |
        docker exec basketball-container /bin/sh -c "while [ ! -f /app/output/logs/run_sequence.log ]; do sleep 5; done; tail -f /app/output/logs/run_sequence.log | sed '/All scripts completed successfully/q'"

    - name: Check for successful completion
      run: |
        if docker exec basketball-container grep -q "All scripts completed successfully" /app/output/logs/run_sequence.log; then
          echo "CI Test passed successfully"
          exit 0
        else
          echo "CI Test failed"
          exit 1
        fi

    - name: Clean up
      if: always()
      run: docker rm -f basketball-container