# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Game Simulation

on:
  push:
    branches: [ "DEV_Code" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest
    env:
      OPENCV_HEADLESS: 1

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r Requirements.txt
      shell: bash

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      shell: bash
      
    - name: Run Basketball Game Simulation script
      run: python "./Basketball_Game_Simulation.py" > game_simulation_output.log
      shell: bash

    - name: Display Log File Contents
      run: cat game_simulation_output.log
      shell: bash

    - name: Run Script and Check Results
      run: |
        if grep -q "Game Simulation succeeded" game_simulation_output.log; then
          echo "Success message found: Test passed."
        else
          echo "Success message not found: Test failed."
          exit 1
        fi
      shell: bash
    
    