name: Basketball Simulation and Tracking Test

on:
  push:
    branches:
      - 'main'
      - 'DEV_Code'
  pull_request:
    branches:
      - 'main'
      - 'DEV_Code'

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r Requirements.txt
      shell: bash
    
    - name: Run Basketball Game Simulation
      run: 
        python Basketball_Game_Simulation.py

        if [ $? -eq 0 ]; then
          echo "Basketball Game Simulation completed successfully"
        else
          echo "Basketball Game Simulation failed"
          exit 1
        fi
      
    - name: Run Basketball Object Tracking
      run: 
        python Basketball_Object_Tracking.py

        if [ $? -eq 0 ]; then
          echo "Basketball Game Simulation completed successfully"
        else
          echo "Basketball Game Simulation failed"
          exit 1
        fi