name: Update Release Version

on:
  push:
    branches:
      - DEV_Code

jobs:
  update-release:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current version
      id: get_version
      run: |
        if [ -f VERSION ]; then
          CURRENT_VERSION=$(cat VERSION)
        else
          echo "0.0.0" > VERSION
          CURRENT_VERSION="0.0.0"
        fi
        echo "Current version is $CURRENT_VERSION"
        echo "::set-output name=current_version::$CURRENT_VERSION"

    - name: Extract version and details from commit message
      id: extract_info
      run: |
        COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
        NEW_VERSION=$(echo "$COMMIT_MESSAGE" | head -n 1 | grep -E '^[0-9]+\.[0-9]+\.[0-9]+')
        UPDATE_DETAILS=$(echo "$COMMIT_MESSAGE" | tail -n +2)
        
        if [[ -z "$NEW_VERSION" ]]; then
          NEW_VERSION="${{ steps.get_version.outputs.current_version }}"
          UPDATE_DETAILS="No details provided."
        fi
        
        echo "New version is $NEW_VERSION"
        echo "Update details: $UPDATE_DETAILS"
        echo $NEW_VERSION > VERSION
        echo "::set-output name=new_version::$NEW_VERSION"
        echo "::set-output name=update_details::$UPDATE_DETAILS"

    - name: Commit and push new version
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add VERSION
        git commit -m "Bump version to ${{ steps.extract_info.outputs.new_version }}"
        git push origin DEV_Code

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.extract_info.outputs.new_version }}
        name: Release ${{ steps.extract_info.outputs.new_version }}
        body: ${{ steps.extract_info.outputs.update_details }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
