# This workflow will install Python dependencies, run tests and lint with a single version of Python 
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Testing of Game Simulation and Object Tracking

on:
  push:
    branches: [ "DEV_Code" ]

permissions:
  contents: read

env:
  OPENCV_HEADLESS: 1

jobs:
  setup:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r Requirements.txt
      shell: bash
    - name: Check Python and pip versions
      run: |
        python --version
        pip --version

  game-simulation:
    needs: setup
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Basketball Game Simulation
      run: python "./Basketball_Game_Simulation.py" > game_simulation_output.log
      shell: bash
    - name: Display Log File Contents
      run: cat game_simulation_output.log
      shell: bash
    - name: Check Results
      run: |
        if grep -q "Game Simulation succeeded" game_simulation_output.log; then
          echo "Success message found: Test passed."
        else
          echo "Success message not found: Test failed."
          exit 1
        fi
      shell: bash

  object-tracking:
    needs: setup
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Basketball Object Tracking
      run: python "./Basketball_Object_Tracking.py" > object_tracking_output.log
      shell: bash
    - name: Display Log File Contents
      run: cat object_tracking_output.log
      shell: bash
    - name: Check Results
      run: |
        if grep -q "Object Tracking succeeded" object_tracking_output.log; then
          echo "Success message found: Test passed."
        else
          echo "Success message not found: Test failed."
          exit 1
        fi
      shell: bash
